# Generated by Django 3.2.3 on 2021-07-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Convolution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('source_coordinate', models.FloatField(max_length=200)),
                ('destination_coordinate', models.FloatField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='towername',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Convolution.corridorline'),
        ),
    ]
