# Generated by Django 3.2.3 on 2021-07-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convolution', '0003_auto_20210716_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridorline',
            name='source_coordinate_lat',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corridorline',
            name='source_coordinate_long',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
