# Generated by Django 3.2.3 on 2021-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convolution', '0004_auto_20210716_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towerimage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
