# Generated by Django 3.2.3 on 2021-09-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Convolution', '0006_towerimages_towerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerimages',
            name='tower_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Convolution.corridorline'),
        ),
    ]
